import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background:  "var(--background)",
        foreground:  "var(--foreground)",
        border:      "var(--border)",
        input:       "var(--input)",
        ring:        "var(--ring)",
        card:        { DEFAULT: "var(--card)", foreground: "var(--card-foreground)" },
        popover:     { DEFAULT: "var(--popover)", foreground: "var(--popover-foreground)" },
        primary:     { DEFAULT: "var(--primary)", foreground: "var(--primary-foreground)" },
        secondary:   { DEFAULT: "var(--secondary)", foreground: "var(--secondary-foreground)" },
        muted:       { DEFAULT: "var(--muted)", foreground: "var(--muted-foreground)" },
        accent:      { DEFAULT: "var(--accent)", foreground: "var(--accent-foreground)" },
        destructive: { DEFAULT: "var(--destructive)" },
        pv: {
          navy:   '#0C1F35',
          blue:   '#1A4F7A',
          accent: '#2E8FC0',
          teal:   '#1DA6A0',
          amber:  '#E09B3D',
          red:    '#D94F4F',
          green:  '#2A9B6F',
          purple: '#7C5CBF',
          white:  '#F8FAFB',
          gray:   '#8A9BB0',
        },
      },
      fontFamily: {
        sans:     ['var(--font-dm-sans)', 'sans-serif'],
        mono:     ['var(--font-dm-mono)', 'monospace'],
        display:  ['var(--font-playfair)', 'serif'],
      },
      keyframes: {
        fadeIn:   { from: { opacity: '0' }, to: { opacity: '1' } },
        msgIn:    { from: { opacity: '0', transform: 'translateX(10px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        newItem:  { from: { opacity: '0', transform: 'translateY(-8px)', background: 'rgba(124,92,191,0.2)' }, to: { opacity: '1', transform: 'translateY(0)', background: 'rgba(255,255,255,0.04)' } },
        typingDot:{ '0%,60%,100%': { transform: 'translateY(0)', opacity: '0.4' }, '30%': { transform: 'translateY(-4px)', opacity: '1' } },
        pulse:    { '0%,100%': { opacity: '1', boxShadow: '0 0 0 0 rgba(29,166,160,0.4)' }, '50%': { opacity: '0.7', boxShadow: '0 0 0 5px rgba(29,166,160,0)' } },
        spin:     { to: { transform: 'rotate(360deg)' } },
        modalIn:  { from: { opacity: '0', transform: 'translateY(20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
      },
      animation: {
        fadeIn:    'fadeIn 0.2s ease',
        msgIn:     'msgIn 0.4s ease both',
        newItem:   'newItem 0.5s ease both',
        typingDot: 'typingDot 1.2s infinite',
        pulse:     'pulse 2s infinite',
        spin:      'spin 0.8s linear infinite',
        modalIn:   'modalIn 0.3s ease',
      },
    },
  },
  safelist: [
    { pattern: /^(bg|text|border|ring|outline)-pv-/ },
    { pattern: /^bg-pv-/, variants: ['hover', 'focus', 'active'] },
    'bg-pv-accent/10', 'bg-pv-accent/15', 'bg-pv-accent/20', 'bg-pv-accent/25',
    'bg-pv-green/8',   'bg-pv-green/10',  'bg-pv-green/15', 'bg-pv-green/18', 'bg-pv-green/20',
    'bg-pv-amber/8',   'bg-pv-amber/10',  'bg-pv-amber/18', 'bg-pv-amber/20',
    'bg-pv-red/8',     'bg-pv-red/10',    'bg-pv-red/18',   'bg-pv-red/20',
    'bg-pv-purple/8',  'bg-pv-purple/10', 'bg-pv-purple/12','bg-pv-purple/20',
    'bg-white/4', 'bg-white/5', 'bg-white/6', 'bg-white/8', 'bg-white/10',
    'border-pv-green/30', 'border-pv-green/50',
    'border-pv-amber/30', 'border-pv-amber/50',
    'border-pv-red/30',   'border-pv-red/50',
    'border-pv-accent/15','border-pv-accent/30','border-pv-accent/40',
    'border-pv-purple/20','border-pv-purple/25','border-pv-purple/40',
    'border-white/8', 'border-white/10', 'border-white/15', 'border-white/20',
    'text-pv-green',  'text-pv-amber',  'text-pv-red',    'text-pv-accent',
    'text-pv-gray',   'text-pv-white',  'text-pv-purple', 'text-pv-teal',
  ],
  plugins: [],
};
export default config;
